config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :users do
    member do
      get :likes
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes do
    resources :likes, only: [:create, :destroy]
  end

  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user 
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_recipes, through: :likes, source: :recipe

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  def already_liked?(recipe)
    self.likes.exists?(recipe_id: recipe.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
      def create
        like = current_user.likes.create(recipe_id: params[:recipe_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(recipe_id: params[:recipe_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :authenticate_user!

    
    def index
        if params[:search] == nil
            @recipes= Recipe.all
        elsif params[:search] == ''
            @recipes= Recipe.all
        else
            #部分検索
            @recipes = Recipe.where("menu LIKE ? ",'%' + params[:search] + '%')
        end
      
    
        
        
        @syusais = Recipe.where(category: "syusai")
        @hukusais = Recipe.where(category: "hukusai")
        @sirumonos = Recipe.where(category: "sirumono")
        @sonotas = Recipe.where(category: "sonota")
    end
    

    def new
        @recipe = Recipe.new
    end
    
    def create
        recipe = Recipe.new(recipe_params)
        recipe.user_id = current_user.id
      if recipe.save
          redirect_to :action => "index"
      else
          redirect_to :action => "new"
      end
    end
    
    def show
        @recipe = Recipe.find(params[:id])
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end
    
    def update
        recipe = Recipe.find(params[:id])
        if recipe.update(recipe_params)
          redirect_to :action => "show", :id => recipe.id
        else
          redirect_to :action => "index"
        end
    end

    def destroy
        recipe = Recipe.find(params[:id])
        recipe.destroy
        redirect_to action: :index
    end
    
    private
    def recipe_params
        params.require(:recipe).permit(:menu, :material, :process, :image, :category)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
      def likes
        likes = Like.where(user_id: @user.id).pluck(:recipe_id)
        @like_recipes = Recipe.find(likes)
      end

      def show
        @user = User.find(params[:id]) 
      end
    
    private
      def set_user
        @user = User.find(params[:id])
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div class="wrapper">
 <div class="container">
  <head>
    <title>Cooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3c922830b1.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <header>
      <h1>FOOODY</h1>
      <a class="circle" href="~"></a>
      <div class="header-list">
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to "New recipe",new_recipe_path %></li>
            <li><%= link_to "My page", user_path(current_user.id) %></li>
            <li><%= button_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <a href="http://localhost:3000/recipes" class="btn btn-border-shadow btn-border-shadow--color">Home</a>
          <% end %>
          
        </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    </div>
    <footer>
      <p>FOOODY</p>
      <a>Copyright © Cooking All Rights Reserved.</a>
    </footer>
  </body>
</div>
</html>

app/views/recipes/_recipe.html.erb
<%= link_to image_tag(recipe.image.variant(resize: '100x100') ), recipe_path(recipe.id) %>
<%= link_to recipe.user.name, user_path(recipe.user.id) %>
<i class="fa fa-heart unlike-btn"></i>
<%= recipe.likes.length %>
<%= link_to recipe.title, recipe_path(recipe.id) %>

app/views/recipes/edit.html.erb
<%= form_for @recipe do |f| %>

<div class= "sets">
  <div class= "set1">

    <h3>料理名</h3>
    <div class="field_ryourimei">
      <%= f.text_field :menu, class: "field_input", :size => 30 %> 
    </div>

    <h3>分類</h3>
    <div class="field_bunrui"> 
      <%= f.select :category, [["主菜", "syusai"], ["副菜", "hukusai"], ["汁物", "sirumono"], ["その他", "sonota"]], include_blank: "どの分類？" %>
    </div>

    <h3>材料</h3>
    <div class="field_zairyou">
      <%= f.text_area :material, :size=>"50x15" %> 
    </div>

    <h3>作り方</h3>
    <div class="field_tsukurikata">
      <%= f.text_area :process, :size=>"50x20" %> 
    </div>
  </div>

  <div class= "set2">
    <h3>画像</h3>
    <div class="field">
      <%= f.file_field :image, id:"file-input",onchange:"previewImage()" %></p>
      <img id="image-preview" src="#" alt="Image Preview" hidden/>
    </div>
  </div>
</div>

  <div class= "button">
    <%= f.submit "レシピを編集する", class:"btn" %>
  </div>
    
<% end %>

<script>
  // プレビュー表示
  const previewImage = () => {
    const fileInput = document.getElementById("file-input");
    const imagePreview = document.getElementById("image-preview");
    if (fileInput.files && fileInput.files[0]) {
      const reader = new FileReader();
      reader.onload = (e) => (imagePreview.src = e.target.result);
      reader.readAsDataURL(fileInput.files[0]);
      imagePreview.hidden = false;
    }
  };
</script>

app/views/recipes/index.html.erb
<div class="top">
  <div class="topimage4">
   <p>FOOODY</p>

    
    <a><%= form_tag({controller:"recipes",action:"index"}, method: :get) do %>
      
        <%= text_field_tag :search %>
        <%= submit_tag '検索する'  %>
       <% end %>
      
    <a/>
  </div>
</div>

<div class= "recipe">
</div>


<div class= "headline">
  <h2>主菜</h2>
</div>

<div class= "syusais-container">
    
    <% @syusais.each do |t| %>
    
    <div class= "syusaitati">
      <div class= "image">
        <% if t.image? %>
          <%= image_tag t.image_url, size: "250x200" %>
        <% else %>
          <div class= "topimage6">
            <p>No Image</p>
          </div>
        <% end %>
      </div>

      <div class= "menu">
        <p><%= t.menu %></p>
      </div>

      <div class= "like">
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to recipe_like_path(id: t.id, recipe_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to recipe_likes_path(id: t.id, recipe_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
      </div>
      
      <div class= "others">
        <p class="more-btn"><%= link_to "詳細へ", recipe_path(t.id) %></p>
        <p class="more-btn"><%= link_to "編集する", edit_recipe_path(t.id) %></p>
        <%= button_to "削除する", recipe_path(t.id), method: :delete %>
      </div>

    </div>

    <% end %>   
</div>


<div class= "headline">
  <h2>副菜</h2>
</div>

<div class= "hukusais-container">
    
    <% @hukusais.each do |t| %>
    
    <div class= "hukusaitati">
      <div class= "image">
        <% if t.image? %>
          <%= image_tag t.image_url, size: "250x200" %>
        <% else %>
          <div class= "topimage6">
            <p>No Image</p>
          </div>
        <% end %>
      </div>

      <div class= "menu">
        <p><%= t.menu %></p>
      </div>

      <div class= "like">
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to recipe_like_path(id: t.id, recipe_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to recipe_likes_path(id: t.id, recipe_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
      </div>

      <p class="more-btn"><%= link_to "詳細へ", recipe_path(t.id) %></p>
      <p class="more-btn"><%= link_to "編集する", edit_recipe_path(t.id) %></p>
      <%= button_to "削除する", recipe_path(t.id), method: :delete %> 
    </div>

    <% end %>   
</div>


<div class= "headline">
  <h2>汁物</h2>
</div>

<div class= "sirumonos-container">
    
    <% @sirumonos.each do |t| %>
    
    <div class= "sirumonotati">
      <div class= "image">
        <% if t.image? %>
          <%= image_tag t.image_url, size: "250x200" %>
        <% else %>
          <div class= "topimage6">
            <p>No Image</p>
          </div>
        <% end %>
      </div>

      <div class= "menu">
        <p><%= t.menu %></p>
      </div>

      <div class= "like">
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to recipe_like_path(id: t.id, recipe_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to recipe_likes_path(id: t.id, recipe_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
      </div>

      <p class="more-btn"><%= link_to "詳細へ", recipe_path(t.id) %></p>
      <p class="more-btn"><%= link_to "編集する", edit_recipe_path(t.id) %></p>
      <%= button_to "削除する", recipe_path(t.id), method: :delete %> 
    </div>

    <% end %>   
</div>


<div class= "headline">
  <h2>その他</h2>
</div>

<div class= "sonotas-container">
    
    <% @sonotas.each do |t| %>
    
    <div class= "sonotatati">
      <div class= "image">
        <% if t.image? %>
          <%= image_tag t.image_url, size: "250x200" %>
        <% else %>
          <div class= "topimage6">
            <p>No Image</p>
          </div>
        <% end %>
      </div>

      <div class= "menu">
        <p><%= t.menu %></p>
      </div>

      <div class= "like">
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to recipe_like_path(id: t.id, recipe_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to recipe_likes_path(id: t.id, recipe_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
      </div>

      <p class="more-btn"><%= link_to "詳細へ", recipe_path(t.id) %></p>
      <p class="more-btn"><%= link_to "編集する", edit_recipe_path(t.id) %></p>
      <%= button_to "削除する", recipe_path(t.id), method: :delete %> 
    </div>

    <% end %>   
</div>

app/views/recipes/new.html.erb
<!--<h1>FOOODY</h1>-->
<h2>新規追加レシピ</h2>
<%= form_for @recipe do |f| %>

<div class= "sets">
  <div class= "set1">
    <h3>料理名</h3>
    <div class="field_ryourimei">
        <%= f.text_field :menu, class: "field_input", :placeholder => " ex.) 肉じゃが" %>
    </div>
  
    <h3>分類</h3>
    <div class= "field_bunrui">
        <%= f.select :category, [["主菜", "syusai"], ["副菜", "hukusai"], ["汁物", "sirumono"], ["その他", "sonota"]], include_blank: "どの投稿？" %>
    </div>

    

    <h3>材料</h3>
    <div class="field_zairyou">
        
        <%= f.text_area :material, :size=>"50x20", class: "area_input", :placeholder => " ex.)
・牛もも肉　　　150ｇ
・じゃがいも　　250ｇ
・にんじん　　　1/2本
・玉ねぎ　　　　1/2個
・水　　　　　　400ml
・醤油　　　　　大3
・サラダ油　　　大1

(A)みりん　　　大2
(A)酒　　　　　大2
(A)砂糖　　　　大1
(A)顆粒和風だし　　小1" %>
    </div>

    
    <h3>作り方</h3>
    <div class="field_tsukurikata">
        <%= f.text_area :process, :size=>"50x20", class: "area_input", :placeholder => " ex.)
①じゃがいもの皮をむいて芽を取り除き、一口大に切る。にんじんは乱切り。玉ねぎはくし切り。
②中火のフライパンにサラダ油をひき、1を入れて炒め、油がなじんだら水を加えて加熱し、沸騰したら肉を入れる。
③アクを取りながら中火で加熱し、肉の色が変わったら(A)を入れる。
④じゃがいもが柔らかくなったら、2、醤油を入れて落し蓋をし、中火で10分程加熱し、味が全体になじんだら完成！" %>
    </div>
    
    

  </div>

  <div class= "set2">
    <h3>写真</h3>
    <div class="image">
      <p><%= f.file_field :image, id:"file-input",onchange:"previewImage()" %></p>
      <img id="image-preview" src="#" alt="Image Preview" hidden/>
    </div>
  </div>
</div>
  
<div class= "button">
  <%= f.submit "レシピを追加する", class:"btn" %>
</div>

<% end %>

<script>
  // プレビュー表示
  const previewImage = () => {
    const fileInput = document.getElementById("file-input");
    const imagePreview = document.getElementById("image-preview");
    if (fileInput.files && fileInput.files[0]) {
      const reader = new FileReader();
      reader.onload = (e) => (imagePreview.src = e.target.result);
      reader.readAsDataURL(fileInput.files[0]);
      imagePreview.hidden = false;
    }
  };
</script>


    

app/views/recipes/show.html.erb
<h2>レシピの詳細</h2>

<div class="sets">
  <div class= "set1">
    <h3>料理名</h3>
    <p><%= @recipe.menu %></p>

    
  
    <h3>材料</h3>
    <p><%= @recipe.material %></p>

    <h3>作り方</h3>
    <p><%= @recipe.process %></p>

    <p><%= @recipe.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@recipe) %>
        <%= button_to recipe_like_path(@recipe), method: :delete do %>
           <i class="fas fa-heart"></i><%= @recipe.likes.count %>
      <% end %>
    <% else %>
      <%= button_to recipe_likes_path(@recipe), method: :post do %>
        <i class="far fa-heart"></i><%= @recipe.likes.count %>
      <% end %>
    <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= @recipe.likes.count %>
    <% end %>
  </div>

  <div class= "set2">

    <h3>画像</h3>
    <div class= "image">
      <% if @recipe.image? %>
        <%= image_tag @recipe.image_url, size: "450x300" %>
      <% else %>
        <div class= "topimage6">
          <p>No Image</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

<p class="more-btn"><%= link_to "編集する", edit_recipe_path(@recipe.id) %></p>

app/views/users/followers.html.erb
<p>お気に入りのレシピ一覧</p>
<%= render partial: "recipes/recipe", collection: @like_recipes %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2>マイページ</h2>

<h3>プロフィール</h3>
<div class= "profile">
  <p>名前 : <%= @user.name %></p>
  <p>メールアドレス : <%= @user.email %></p>
  <p>プロフィール : <%= @user.profile %></p>
</div>

<% if current_user.id == @user.id %>
  <p class="more-btn"><%= link_to "編集する", edit_user_registration_path %></p>
<% end %>


<h2>お気に入りのレシピ一覧</h2>

<div class= "okiniiris-container">
<% @user.liked_recipes.each do |t| %>

  <div class="okiniiri">
  
    <div class= "image">
      <% if t.image? %>
        <%= image_tag t.image_url, size: "250x200" %>
      <% else %>
        <div class= "topimage6">
          <p>No Image</p>
        </div>
      <% end %>
    </div>

    <div class= "menu">
      <p><%= t.menu %></p>
    </div>

    <div class= "like">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to recipe_like_path(id: t.id, recipe_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to recipe_likes_path(id: t.id, recipe_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
        <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>
    </div>

    <p class="more-btn"><%= link_to "詳細へ", recipe_path(t.id) %></p>
    <p class="more-btn"><%= link_to "編集する", edit_recipe_path(t.id) %></p>
    <%= button_to "削除する", recipe_path(t.id), method: :delete %> 

  </div>
<% end %>
</div>